const BEARER_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaXZlX2RpZ2l0YWxvbmVib3giLCJleHAiOjE2NTg0OTM3NjF9.yV6Zb6xSdb4WUOFGjrISj3p8abINxOCz0UbsGTqQ_S8";
module.exports = { BASEURL, BEARER_TOKEN };
